  name: terraform
  # Controls when the workflow will run
  on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches:
        - main



    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: azure-terraform

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: checkout
         uses: actions/checkout@v3

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
         with:
            Terraform version: v1.6.5

       - name: terraform init
         id: init
         run: terraform init

       - name: terraform plan
         id: plan
         run: terraform plan

       - name: terraform apply
         id: apply
         run: terraform apply --auto-approve
 
